"""Property test for the Signal Reader's tool-call retry and timeout behavior.

Covers the bounded retry loop of the seam-backed Signal Reader
(``forecast.signals.read_signals`` -> ``_call_read_only_tool``): each read-only
tool is attempted up to ``MAX_ATTEMPTS`` (3) times, with exponential backoff of
1s then 2s (``BACKOFF_SEQUENCE_SECONDS``) slept between attempts via the injected
``sleep`` seam. The loop stops early on the first success (no further attempts
or backoff), and a per-call timeout is treated as a FAILED attempt that triggers
a retry exactly like any other failure (Req 8.5).

The reader's timeout runner and backoff sleep are injectable seams, so this test
drives attempt counts and the backoff sequence deterministically WITHOUT any
wall-clock delay. A small stateful fake (:class:`StatefulToolFake`) models a
per-tool SEQUENCE of attempt outcomes (``"success"`` / ``"fail"`` / ``"timeout"``)
generated by Hypothesis and records, per tool, how many attempts were made and
which backoff seconds were slept, so both are inspectable in the assertions.

Validates: Requirements 2.6, 8.5.
"""

from __future__ import annotations

from typing import Any, Callable

from hypothesis import given, settings
from hypothesis import strategies as st

from forecast.engine import ForecastHorizon
from forecast.signals import (
    BACKOFF_SEQUENCE_SECONDS,
    MAX_ATTEMPTS,
    TOOL_GET_OCCUPANCY,
    TOOL_GET_REVENUE,
    TOOL_GET_SISTER_PROPERTY_AVAILABILITY,
    read_signals,
)

# Minimum property-based iterations mandated by the design Testing Strategy.
PROPERTY_SETTINGS = settings(max_examples=100)

# The single bound run property every tool call is scoped to (Req 2.4, 6.1).
RUN_PROPERTY_ID = "ALOHA-CHI-001"

# The three possible per-attempt outcomes the fake models. "success" returns a
# canned result; "fail" raises a RuntimeError; "timeout" raises TimeoutError so
# the reader's retry loop treats it as a timed-out (failed) attempt (Req 8.5).
OUTCOME_SUCCESS = "success"
OUTCOME_FAIL = "fail"
OUTCOME_TIMEOUT = "timeout"
OUTCOMES = (OUTCOME_SUCCESS, OUTCOME_FAIL, OUTCOME_TIMEOUT)

# The tools read_signals invokes when overflow is not needed (Phase 1 only).
OCCUPANCY_REVENUE_TOOLS = (TOOL_GET_OCCUPANCY, TOOL_GET_REVENUE)


class StatefulToolFake:
    """A stateful fake driving per-tool attempt outcomes for the retry loop.

    Models an independent SEQUENCE of attempt outcomes per tool. Each call to
    :meth:`call_tool` consumes the next outcome for that tool and either returns
    a canned result (``"success"``), raises ``RuntimeError`` (``"fail"``), or
    raises ``TimeoutError`` (``"timeout"``). A ``TimeoutError`` propagates through
    the pass-through :meth:`timeout_runner` seam so the reader's retry loop treats
    it as a timed-out attempt (Req 8.5), exactly as a real timeout runner would.

    Per tool it records the number of attempts made (:attr:`attempts`) and the
    backoff seconds slept before each retry (:attr:`sleeps`), so a test can assert
    on attempt counts and the exact backoff sequence.

    Attributes:
        sequences: Mapping of tool name -> list of attempt outcome strings.
        attempts: Mapping of tool name -> count of attempts actually consumed.
        sleeps: Mapping of tool name -> list of backoff seconds slept, in order.
    """

    def __init__(self, sequences: dict[str, list[str]]) -> None:
        """Initialize with a per-tool sequence of attempt outcomes.

        Args:
            sequences: Mapping of tool name to its ordered list of attempt
                outcomes, each one of :data:`OUTCOMES`.
        """
        self.sequences = sequences
        self.attempts: dict[str, int] = {name: 0 for name in sequences}
        self.sleeps: dict[str, list[float]] = {name: [] for name in sequences}
        # The tool whose attempt is currently in flight, so the sleep seam can
        # attribute a recorded backoff to the right tool (read_signals calls the
        # tools sequentially, one fully-resolved before the next begins).
        self._current_tool: str | None = None

    def call_tool(self, tool_name: str, arguments: dict[str, Any]) -> Any:
        """Consume the next outcome for ``tool_name`` and act on it.

        Args:
            tool_name: The bare tool name being invoked by the reader.
            arguments: The tool arguments (carrying ``propertyId``); unused here
                beyond being accepted to match the ToolCaller seam shape.

        Returns:
            A canned result dict scoped to the bound run property when the next
            outcome is ``"success"``.

        Raises:
            RuntimeError: When the next outcome is ``"fail"`` (a generic tool
                failure).
            TimeoutError: When the next outcome is ``"timeout"`` - propagated
                through the timeout runner so the retry loop counts it as a
                timed-out attempt (Req 8.5).
        """
        self._current_tool = tool_name
        attempt_index = self.attempts[tool_name]
        self.attempts[tool_name] += 1
        outcome = self.sequences[tool_name][attempt_index]

        if outcome == OUTCOME_SUCCESS:
            # A canned, isolation-clean result: a single record already scoped to
            # the bound property so the reader's property-isolation filter keeps
            # it and records no discrepancy (keeps this test about retry only).
            return {"records": [{"propertyId": RUN_PROPERTY_ID, "value": 1}]}
        if outcome == OUTCOME_FAIL:
            raise RuntimeError(f"tool {tool_name} failed (test)")
        # OUTCOME_TIMEOUT: raise a builtin TimeoutError so the reader maps it to a
        # timed-out attempt, identical handling to any other failure (Req 8.5).
        raise TimeoutError(f"tool {tool_name} timed out (test)")

    def timeout_runner(self, thunk: Callable[[], Any], timeout_seconds: float) -> Any:
        """Pass-through timeout runner: run ``thunk`` and surface its outcome.

        Deterministic stand-in for the real thread-based runner. It runs the
        thunk directly (no threads, no clock); a ``TimeoutError`` raised by the
        fake tool propagates through unchanged, which is exactly how a real
        timeout would surface out of the runner into the retry loop (Req 8.5).

        Args:
            thunk: The zero-argument callable performing one tool invocation.
            timeout_seconds: The per-call timeout budget; unused by the fake.

        Returns:
            Whatever ``thunk`` returns on a ``"success"`` outcome.
        """
        return thunk()

    def sleep(self, seconds: float) -> None:
        """Record a backoff sleep against the tool currently being retried.

        Args:
            seconds: The backoff duration the reader asked to sleep. Recorded
                (not actually slept) so the backoff sequence is inspectable.
        """
        assert self._current_tool is not None
        self.sleeps[self._current_tool].append(seconds)


def _horizon() -> ForecastHorizon:
    """Return a fixed, valid horizon (its dates are irrelevant to retry logic)."""
    return ForecastHorizon(start_date="2025-01-01", end_date="2025-01-15")


def _truncate_after_first_success(outcomes: list[str]) -> list[str]:
    """Return the prefix of ``outcomes`` up to and including the first success.

    Mirrors the reader's early-stop behavior so the EXPECTED consumed attempts
    can be derived independently of the implementation: the loop stops on the
    first success, so any outcomes after a success are never consumed.

    Args:
        outcomes: The full generated outcome sequence for one tool.

    Returns:
        The consumed prefix - all leading failures/timeouts plus the first
        success, or the whole (capped) list when no success occurs.
    """
    consumed: list[str] = []
    for outcome in outcomes:
        consumed.append(outcome)
        if outcome == OUTCOME_SUCCESS:
            break
    return consumed


# A per-tool outcome sequence: 1..MAX_ATTEMPTS outcomes, each success/fail/timeout.
# Capped at MAX_ATTEMPTS since the reader never makes more than that many attempts.
_outcome_sequence = st.lists(
    st.sampled_from(OUTCOMES),
    min_size=1,
    max_size=MAX_ATTEMPTS,
)


def _pad_to_max_attempts(outcomes: list[str]) -> list[str]:
    """Pad a generated sequence to MAX_ATTEMPTS with trailing failures.

    The reader retries any non-success up to ``MAX_ATTEMPTS`` total attempts, so
    the fake MUST have a defined outcome for every attempt it could make. Padding
    a short sequence with ``"fail"`` (a non-success, which keeps retrying) makes
    the fake's per-attempt behavior fully specified without changing the modeled
    stop-on-first-success semantics: a padded ``"fail"`` is only ever reached when
    no earlier success occurred.

    Args:
        outcomes: The generated (possibly short) outcome sequence for one tool.

    Returns:
        A list of exactly ``MAX_ATTEMPTS`` outcomes.
    """
    padded = list(outcomes)
    while len(padded) < MAX_ATTEMPTS:
        padded.append(OUTCOME_FAIL)
    return padded


# ---------------------------------------------------------------------------
# Property 6: Tool-call retry and timeout behavior
# ---------------------------------------------------------------------------


# Feature: predictive-forecasting-agent, Property 6: Tool-call retry and timeout behavior
@PROPERTY_SETTINGS
@given(
    occupancy_outcomes=_outcome_sequence,
    revenue_outcomes=_outcome_sequence,
)
def test_property_6_tool_call_retry_and_timeout(
    occupancy_outcomes: list[str],
    revenue_outcomes: list[str],
) -> None:
    """Retry loop: <=3 attempts, stops on first success, timeout == failed attempt.

    For independently generated per-tool outcome sequences (occupancy and
    revenue, ``needs_overflow=False`` to keep the read to Phase 1), asserts:

    - No tool makes more than ``MAX_ATTEMPTS`` (3) attempts.
    - The loop STOPS on the first success: attempts consumed equal the prefix up
      to and including the first success (nothing after a success runs).
    - A timeout is treated as a failed attempt: it triggers a retry just like a
      ``fail`` (a sequence like ``[timeout, success]`` still succeeds on the 2nd
      attempt), which the attempt-count and success-derivation checks capture.
    - The backoff seconds slept before each retry match the prefix of
      ``BACKOFF_SEQUENCE_SECONDS`` == (1.0, 2.0): sleep(1.0) after the 1st failed
      attempt, sleep(2.0) after the 2nd; no sleep after a success or after the
      final attempt.
    """
    # Pad each sequence to MAX_ATTEMPTS so the fake has a defined outcome for
    # every attempt the reader might make (it retries non-successes up to 3).
    sequences = {
        TOOL_GET_OCCUPANCY: _pad_to_max_attempts(occupancy_outcomes),
        TOOL_GET_REVENUE: _pad_to_max_attempts(revenue_outcomes),
    }
    fake = StatefulToolFake(sequences)

    result = read_signals(
        RUN_PROPERTY_ID,
        _horizon(),
        fake.call_tool,
        needs_overflow=False,
        timeout_runner=fake.timeout_runner,
        sleep=fake.sleep,
    )

    for tool_name in OCCUPANCY_REVENUE_TOOLS:
        outcomes = sequences[tool_name]
        expected_consumed = _truncate_after_first_success(outcomes)
        attempts_made = fake.attempts[tool_name]

        # No tool exceeds MAX_ATTEMPTS (3) attempts.
        assert attempts_made <= MAX_ATTEMPTS

        # The loop stops on the first success: attempts consumed equal the prefix
        # up to and including the first success (or the whole sequence when none
        # succeeds). This also encodes "timeout is a failed attempt" - a timeout
        # is NOT a stop, only a success is.
        assert attempts_made == len(expected_consumed)

        # If the consumed prefix ended in a success, no attempt ran after it.
        succeeded = expected_consumed[-1] == OUTCOME_SUCCESS
        if succeeded:
            assert expected_consumed.count(OUTCOME_SUCCESS) == 1

        # A tool that never succeeds is degraded gracefully into missing_signals
        # (and its consumed attempts are the full capped sequence).
        if not succeeded:
            assert tool_name in result.missing_signals
        else:
            assert tool_name not in result.missing_signals

        # Backoff: one sleep before each retry, so the number of sleeps is the
        # number of consumed attempts minus one, and never more than the two
        # available backoff gaps.
        expected_sleeps = list(BACKOFF_SEQUENCE_SECONDS[: len(expected_consumed) - 1])
        assert fake.sleeps[tool_name] == expected_sleeps
        assert BACKOFF_SEQUENCE_SECONDS == (1.0, 2.0)

    # A [timeout, success] style sequence must succeed on the 2nd attempt: no
    # tool that ends in success is reported missing (checked above per tool).
